### ISSUE TITLE
Add support for arcade sticks 

### ISSUE THREAD

**Issue by DGMurdockIII** [RetroBat-Official/retrobat-setup#108]
Can u guys add support for non ximput arcade sticks for example I have the xarcade tankstick

**Comment by TheDayG0ne** [comment]
Hi guys! I suggest you find a solution together. We received the same Issue with xarcade support

**Comment by Tartifless** [comment]
Hello,
You are free to participate and do a PR to fix it.

**Comment by Tartifless** [comment]
Did you try xinput or dinput mode:
![iLeBR4wP3sV7kHnCjYE8wDiQJ0bndeR2-Q](https://github.com/RetroBat-Official/retrobat-setup/assets/13442986/cad935fd-6ed5-4a8b-9fae-b7116181003a)

**Comment by TheDayG0ne** [comment]
> Hello,
> 
> You are free to participate and do a PR to fix it.

https://github.com/PRO100BYTE/ProjectArcade/issues/53

**Comment by Tartifless** [comment]
> > Hello,
> > You are free to participate and do a PR to fix it.
> 
> [PRO100BYTE/ProjectArcade#53](https://github.com/PRO100BYTE/ProjectArcade/issues/53)

I only see a reference to this issue, no support added.

Also, Xarcade offers a change of PCB to allow the stick to be used as 2 x-input controllers, so we will not do anything as it is covered by the manufacturer.

https://shop.xgaming.com/products/any-x-arcade-2022-upgrade-kit

**Comment by DGMurdockIII** [comment]
OK I'll have to try it

**Comment by TheDayG0ne** [comment]
> > [PRO100BYTE/ProjectArcade#53](https://github.com/PRO100BYTE/ProjectArcade/issues/53)
> 
> I only see a reference to this issue, no support added.

We are working on a solution to the problem...

**Comment by DGMurdockIII** [comment]
How is this going
