### ISSUE TITLE
support for Xbox Live Arcade titles

### ISSUE THREAD

**Issue by udance4ever** [RetroBat-Official/retrobat-setup#122]
In Batocera Linux, this is done through the addition of a `.xbox360` file containing the path to the XBLA file and uses this code in configgen:

https://github.com/batocera-linux/batocera.linux/blob/9032219691eb724ed76c39f75907a2a9237f3a0c/package/batocera/core/batocera-configgen/configgen/configgen/generators/xenia/xeniaGenerator.py#L147-L163

I’m poking around Retrobat source code and I don’t get the sense Retrobat is executing full-blown Python.

I found an easy workaround that might be acceptable - use a `.xbla` extension.

It required me to change one line in `es_systems.cfg` and I just created a symlink to the data file - for example for Ilomilo:
```
Ilomilo.xbla -> D2BAC6E5571A96D5BB3CEF0F1A3F4F25709C951358
```
ES finds the file either location:
```
roms\xbox360\Ilomilo.xbla
roms\xbox360\Ilomilo\58410A1B\000D0000\Ilomilo.xbla
```

In this way, both implementations (.xbox360 and .xbla) can co-exist in a dual boot RetroBat and Batocera Linux setup.

**Comment by Tartifless** [comment]
Hello,
What is the problem you have with xbla games ?

**Comment by udance4ever** [comment]
this is great!  thank you for the pointer to your wiki - I can see it is a rich resource.

I will give creating a .m3u a shot.
