### ISSUE TITLE
Xenia: add d3d12_debug to Advanced Game Options

### ISSUE THREAD

**Issue by udance4ever** [RetroBat-Official/retrobat-setup#123]
[This video on Xbox 360 emulation on a ROG Ally Extreme](https://www.youtube.com/watch?v=HbafRt4yUqc) is pretty impressive and lots of tweaks are required for half the games demonstrated.

Of course, one route would be to go down the path of RPCS3 and ask the Xenia team to support a `custom_config` directory.  The other path (I think of least resistance) would be to implement something rudimentary at the ES level using a pre-launch script hook perhaps.

If written properly, it might be extensible to any system supported by ES in RetroBat (not just Xenia) that requires tinkering of options to get a title to emulate just right.

Targeting Xenia as there is a real need to automate this!

**Comment by Tartifless** [comment]
Our ES implementation allows per-game config, there is no need to modify something at emulator level

**Comment by udance4ever** [comment]
to be clear - I suggested a solution at the ES level - is there a better way to achieve this result in RetroBat?

if you could provide instructions, this would be great!

**Comment by Tartifless** [comment]
Hello,

Look here:
https://wiki.retrobat.org/navigation/configuration-of-systems-and-games

**Comment by udance4ever** [comment]
Now I see what you are getting at - thank you!

Is Refresh Memory Pages State `d3d12_clear_memory_page_state`? (I assume it is)

I combed through what I think is the best [Xbox360 on handhelds showcase video to date](https://www.youtube.com/watch?v=HbafRt4yUqc) (it’s awesome if you haven’t watched it!) and found a new option to add to your next release:

`d3d12_debug` (Too Human)

**Comment by Tartifless** [comment]
Ok we'll ass it to the next version

**Comment by Tartifless** [comment]
Hello @udance4ever : i see no mention of this setting being required for too human ==> where do you see this ?

**Comment by udance4ever** [comment]
https://youtu.be/HbafRt4yUqc?si=PFrzsJ2e23Zvd0_R&t=2665

**Comment by Tartifless** [comment]
Done with https://github.com/RetroBat-Official/emulatorlauncher/pull/579
