### ISSUE TITLE
unable to update to 6.4 from 6.3.1

### ISSUE THREAD

**Issue by EricChan1989** [RetroBat-Official/retrobat-setup#193]
Dear Developer,

I tried to follow your guide to replace the cmd file and then run retrobat.exe and check for updates, however, it still says no update is available.
Could you please help?

Thanks.

**Comment by getupor** [comment]
Hello @EricChan1989 
Have you place the _es-checkversion.cmd_ file in **\emulationstation\**
Have you got some firewall / antivirus running ?

**Comment by EricChan1989** [comment]
Ah, good point.
I put it in system\scripts as there is an exact same name command file there 
Your solution works, thanks.
