### ISSUE TITLE
Teknoparrot is missing a system icon

### ISSUE THREAD

**Issue by Monkee-code** [RetroBat-Official/retrobat-setup#208]
![Screenshot 2024-11-10 234334](https://github.com/user-attachments/assets/d572b16e-4760-4716-9140-f05d12be8df2)

**Comment by Tartifless** [comment]
I think this is related to the theme you are using.
Default theme provided with Retrobat has one

**Comment by Monkee-code** [comment]
I see. Thank you for the explanation!
