### ISSUE TITLE
Mame64 > wrong display with default_unglazed overlay

### ISSUE THREAD

**Issue by getupor** [RetroBat-Official/retrobat-setup#32]
Mame64 only appear wrong with default_unglazed overlay.
All others overlays appear as they should

![2023-11-18_10h16_50](https://github.com/RetroBat-Official/retrobat-setup/assets/83818901/801a861d-00e3-4a74-b011-24228133dc10)

Seems to be due to the defaut_4_3.info that force the height to 240

(Comparaison between retrobat5.3 file and V6beta)
![2023-11-21_10h27_44](https://github.com/RetroBat-Official/retrobat-setup/assets/83818901/4266da25-e591-4249-b4e1-d4a74b4a8f05)

**Comment by Tartifless** [comment]
Fixed
