### ISSUE TITLE
Wrong or missed cores options

### ISSUE THREAD

**Issue by iconoclusterdotexe** [RetroBat-Official/retrobat-setup#38]
Dosbox pure:
- Aspect Ratio Correction has "ratio" variable on the es_features.cfg file. Same as general "Aspect Ratio" option.
- Core Type and Core Mode are inverted. If you see their description, it is completely wrong and the variables do not coincide with the values.
- RAM values are missing: 128, 224, 256, 512, 1024.

Mega drive, TGFX, Nes and Snes cores:
- Fix the "Sprite Limit" to "No Sprite Limit". It has more sense.

Puae and all vice cores:
- Fix the "Auto" value on crop mode. The cores uses "auto" value on them (*_crop_mode) and it makes conflicts with the ES Auto value. A similar issue was in batocera, but it was fixed by assigning a new value named "automatic" value to the core "auto" value on libretroptions script to prevent the conflict.
- Missing the Auto-Disable" (auto_disable value) on all vice cores.

**Comment by Tartifless** [comment]
https://github.com/RetroBat-Official/emulatorlauncher/commit/37550384ee157f742c5f0930ba1503ebf1ebab97

**Comment by Tartifless** [comment]
Hello, this is not an issue ==> auto = Japan, it's a choice

**Comment by Tartifless** [comment]
There is no "auto" value, in v6 of RetroBat, we set now the value "Default" when auto is selected in RetroBat.
Maybe this is the value you are referring to ==> so it will be fixed in v6 also
