### ISSUE TITLE
Add .zar extention for Xbox360 game in es_systems.cfg

### ISSUE THREAD

**Issue by matguitarist** [RetroBat-Official/retrobat-setup#44]
Please add support for .zar format.  It work great for both game and XBLA ( zar is only support by xenia-canary ) 
Game can be compress with Zarchive ( The tool use in CEMU for the WUA format ) ( https://github.com/Exzap/ZArchive ) 
Note that games need to be extract with Wxpirs before running 

Also, maybe separate xbox360 and xbla folder. Same for Wii and Wiiware and PSP and PSP mini. ( only suggestion ) 
I think it might be a great addition. i'm using custom es_system for those es_systems_wiiware.cfg, es_systems_xbla.cfg and es_systems_pspminis.cfg etc ... but i think those can be integrated for everyone.

```
  <system>
    <name>xbox360</name>
    <fullname>Xbox 360</fullname>
    <manufacturer>Microsoft</manufacturer>
    <release>2005</release>
    <hardware>console</hardware>
    <path>~\..\roms\xbox360</path>
    <extension>.iso .xex .xcp .m3u .zar</extension>
    <command>"%HOME%\emulatorLauncher.exe" -gameinfo %GAMEINFOXML% %CONTROLLERSCONFIG% -system %SYSTEM% -emulator %EMULATOR% -core %CORE% -rom %ROM%</command>
    <emulators>
      <emulator name="xenia" />
      <emulator name="xenia-canary" />
    </emulators>
    <platform>xbox360</platform>
    <theme>xbox360</theme>
  </system>

```

**Comment by Tartifless** [comment]
Done
