### ISSUE TITLE
x64

### ISSUE THREAD

**Issue by lauren7ino** [RetroBat-Official/retrobat-setup#74]
Hi
Can you please remove the x64 check from the setup?
Windows 11 on ARMx64 runs everything Windows x32/x64, as Microsoft provides an on the fly assembly translation layer.
Your check prevents us with an ARMx64 Windows from even installing your app, although (probably) would run fine.
Thank you

**Comment by lauren7ino** [comment]
Here, the same problem as this:
https://newsgroup.xnview.com/viewtopic.php?t=46626

**Comment by kaylh** [comment]
Hi
No because we build a setup for x86 64bits. If Windows is able to run 64bit win32 application, you don't need to use build.bat but only to try if RetroBat run actually on Windows ARM with compatibility layer.

**Comment by lauren7ino** [comment]
Yes, after installed it runs perfectly on Windows ARM.
By the way, I'm using a macOS.

I run your setup on an intel machine, and copied the RetroBat folder to Windows ARM64.

Your setup check for x64 can be safely removed, or extended to support ARM64.

![image](https://github.com/RetroBat-Official/retrobat-setup/assets/9194198/84ace96b-e76d-4531-993e-729bdd27a54a)

![image](https://github.com/RetroBat-Official/retrobat-setup/assets/9194198/f341fbc6-7464-4da1-a1cd-327c9d42846d)

**Comment by lauren7ino** [comment]
To clarify, your setup displays this error on Windows ARM, which is incorrect:

![image](https://github.com/RetroBat-Official/retrobat-setup/assets/9194198/582ca3e5-3a1d-4ec3-8551-8e45b1e3c176)

**Comment by kaylh** [comment]
Hi,
I try to respect the requirements from Microsoft sign tools to expect a signature and a certificate for RetroBat's setup, in a near future I hope. I didn't fill yet all the requirements but your asking would take us a step back towards this goal. Because building an ARM setup to install x86 software is weird and can cause security issue. Your way to install retrobat isn't officially supported so if you want to tweak RetroBat for testing purpose you're on your own for now.

**Comment by lauren7ino** [comment]
OK no problem 😊
There are almost no ARM compiled apps and setups, but Windows 11 WOW64 APIs are so good recompiling on the fly Intel to ARM assembly, so you may NEVER need to actually create an ARM version of your software.
You only need to remove that message "This program can only be installed on versions of Windows designed for the following processor architectures: x64", because it's not truth.
ARM64 runs 99.9% of Intel x64 programs and setups.

**Comment by kaylh** [comment]
In your case you probably need only to create a zip archive with build.bat after the "download, configure" (option 2), then archive (option 4)

**Comment by alsom2004** [comment]
@lauren7ino anychance you could link me your pre setup retrobat? I'm also on mac but don't have access to a proper windows computer

**Comment by lauren7ino** [comment]
Yes, this situation is awkward.
The setup runs 100% on ARM64 Windows, but the setup coder decided to check it the machine is Intel, and doesn’t let us proceed.
This is wrong, since Windows ARM64 auto translates Intel code to ARM without user intervention.

**Comment by lauren7ino** [comment]
Worst, last time I checked, the Zip version was not available, so we are out of luck without an Intel Windows.

**Comment by lauren7ino** [comment]
@alsom2004 

7-Zip from RetroBat-v7.1.0-stable-win64-setup.exe

Requires:
DirectX9
Visual C++ 2010-2022 Redistributables (32 & 64 bit)

7-Zip pass: 710 
Link: https://we.tl/t-LYykudyXKK
